
import {
  StoryCard,
  CardType,
  Challenge,
  CateringProvider,
  Product,
  ProductType,
  ProductStyle,
  CharityIssue,
} from './types';

export const storyData: StoryCard[] = [
  {
    id: 1,
    type: CardType.Story,
    organization: '喜憨兒基金會',
    title: '用愛烘焙的每一塊餅乾',
    content: '在我們的烘焙坊, 每一位學員都用心學習, 揉麵、塑形、烘烤... 他們的專注與努力, 都濃縮在您手中的這份美味裡。',
    image: 'https://images.pexels.com/photos/2067405/pexels-photo-2067405.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 2,
    type: CardType.Story,
    organization: '陽光基金會',
    title: '編織希望的向陽小舖',
    content: '傷友們用他們溫柔而堅毅的手, 製作出一件件充滿巧思的手工點心。您的每一次購買, 都是對他們重建生活最大的肯定。',
    image: 'https://images.pexels.com/photos/3026806/pexels-photo-3026806.jpeg',
  },
  {
    id: 101,
    type: CardType.Surprise,
    title: '🌟 驚喜小語 🌟',
    content: '謝謝你, 今天因為你更有意義！感謝您願意花時間了解我們的故事。',
  },
  {
    id: 3,
    type: CardType.Story,
    organization: '伊甸基金會',
    title: '慢飛天使的甜蜜夢想',
    content: '我們的庇護工場, 是慢飛天使們學習與成長的園地。他們在這裡製作蛋糕, 不僅學會一技之長, 更找到自信與歸屬感。',
    image: 'https://images.pexels.com/photos/7552065/pexels-photo-7552065.jpeg',
  },
  {
    id: 4,
    type: CardType.Story,
    organization: '勵馨基金會',
    title: '甜點開啟婦女新人生',
    content: '每一份由受助婦女親手製作的甜點, 都象徵著她們的蛻變與重生。您的支持, 是她們邁向獨立自主的重要力量。',
    image: 'https://images.pexels.com/photos/1055271/pexels-photo-1055271.jpeg',
  },
  {
    id: 102,
    type: CardType.Surprise,
    title: '🎁 專屬優惠 🎁',
    content: '感謝您的關注！下次消費結帳輸入 "GOODBITE10", 即可享九折優惠。',
  },
  {
    id: 5,
    type: CardType.Story,
    organization: '為台灣而教 (TFT)',
    title: '偏鄉孩子的午茶約定',
    content: '我們與在地小農合作, 讓偏鄉孩子參與製作營養點心。您的購買, 將支持我們的教育計畫, 也為孩子帶來溫暖。',
    image: 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

export const challengeData: Challenge[] = [
  {
    id: 'challenge1',
    title: '支持 200 份庇護甜點禮盒, 擴增友善職場工時',
    organization: '樂芽社會企業',
    description: '樂芽由一群熱愛烘焙的庇護員工組成, 每一份甜點都承載著努力與希望。只要集滿 200 份「樂芽手工甜點禮盒」, 我們就能增加 2 位身障學員的正式工作時數, 擴充出每日固定產線, 讓更多人走進職場、活出價值。',
    goal: 200,
    current: 118,
    deadline: '2025-11-20',
    participants: 92,
    image: 'https://images.pexels.com/photos/17939259/pexels-photo-17939259.jpeg',
    productName: '樂芽手工甜點禮盒',
    packages: [
      { id: 'c1p1', name: '獨享支持', price: 450, description: '一人享用, 滿滿心意', contribution: 1 },
      { id: 'c1p2', name: '好友分享 (2盒)', price: 880, description: '與朋友分享雙倍喜悅', contribution: 2 },
      { id: 'c1p3', name: '企業團購 (10盒)', price: 4200, description: '團體力量, 成就更大夢想', contribution: 10 },
    ],
  },
  {
    id: 'challenge2',
    title: '幫助 10 位唐氏青年實習轉正, 達標 600 份幸福點心包',
    organization: '心路基金會',
    description: '每一份「幸福點心包」不只是手工餅乾, 更是庇護青年走入社會的練習。當支持數達到 600 份時, 心路基金會將正式提供 10 位實習青年轉任庇護正職, 進一步穩定工作與生活能力。這不只是點心, 更是改變人生的橋梁。',
    goal: 600,
    current: 388,
    deadline: '2025-11-27',
    participants: 157,
    image: 'https://images.pexels.com/photos/7474300/pexels-photo-7474300.jpeg',
    productName: '幸福點心包',
    packages: [
      { id: 'c2p1', name: '嚐鮮包', price: 300, description: '小份量, 大支持', contribution: 1 },
      { id: 'c2p2', name: '家庭號 (3包)', price: 850, description: '全家共享的幸福滋味', contribution: 3 },
      { id: 'c2p3', name: '辦公室零食箱 (20包)', price: 5500, description: '讓下午茶時間更有意義', contribution: 20 },
    ],
  },
];

export const cateringProviders: CateringProvider[] = [
  {
    id: 'p1',
    name: '喜憨兒烘焙坊',
    specialties: ['手工餅乾', '造型蛋糕'],
    minPeople: 20,
    maxPeople: 100,
    pricePerPerson: 150,
    deliveryTime: '3-5 天',
    issue: '庇護工坊',
    description: '由喜憨兒基金會創辦, 提供心智障礙者專業的烘焙技能訓練。我們的產品不僅美味, 更蘊含著孩子們の努力與成就感。適合各種企業茶會與生日派對。',
    image: 'https://images.pexels.com/photos/890507/pexels-photo-890507.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'p2',
    name: '陽光小舖',
    specialties: ['健康點心', '節慶禮盒'],
    minPeople: 15,
    maxPeople: 80,
    pricePerPerson: 180,
    deliveryTime: '4-6 天',
    issue: '庇護工坊',
    description: '陽光小舖為燒傷及顏損朋友提供一個重返職場的平台。我們堅持使用天然健康的食材, 用心製作每一份點心, 傳遞溫暖與希望。',
    image: 'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'p3',
    name: '勵馨甜點工作室',
    specialties: ['創意口味馬芬', '精緻蛋糕'],
    minPeople: 30,
    maxPeople: 150,
    pricePerPerson: 200,
    deliveryTime: '5-7 天',
    issue: '婦女就業',
    description: '我們協助受暴婦女學習烘焙技能, 找到經濟獨立與自信。每一份甜點都代表著她們的堅韌與新生, 口感層次豐富, 充滿故事性。',
    image: 'https://images.pexels.com/photos/680940/pexels-photo-680940.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'p4',
    name: 'TFT 偏鄉共好廚房',
    specialties: ['在地食材點心', '健康取向餐盒'],
    minPeople: 50,
    maxPeople: 200,
    pricePerPerson: 120,
    deliveryTime: '需要提前 7 天預訂',
    issue: '偏鄉教育',
    description: '結合「為台灣而教」的教育理念, 我們與偏鄉小農合作, 開發出具有在地特色的健康餐點。您的訂購將直接支持偏鄉教育與農業發展。',
    image: 'https://images.pexels.com/photos/1387037/pexels-photo-1387037.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

export const productData: Product[] = [
  {
    id: 'prod1',
    name: '愛心手工餅乾禮盒',
    organization: '喜憨兒基金會',
    price: 350,
    image: 'https://images.pexels.com/photos/461431/pexels-photo-461431.jpeg?auto=compress&cs=tinysrgb&w=800',
    type: ProductType.GiftBox,
    style: ProductStyle.Creative,
    issue: CharityIssue.ShelteredWorkshop,
    dateAdded: '2025-09-28',
    sales: 152,
  },
  {
    id: 'prod2',
    name: '天使檸檬蛋糕',
    organization: '伊甸基金會',
    price: 420,
    image: 'https://images.pexels.com/photos/8478182/pexels-photo-8478182.jpeg',
    type: ProductType.Cake,
    style: ProductStyle.Healthy,
    issue: CharityIssue.ShelteredWorkshop,
    dateAdded: '2025-09-15',
    sales: 350,
  },
  {
    id: 'prod3',
    name: '向陽燕麥棒',
    organization: '陽光基金會',
    price: 280,
    image: 'https://images.pexels.com/photos/6061396/pexels-photo-6061396.jpeg?auto=compress&cs=tinysrgb&w=800',
    type: ProductType.Snack,
    style: ProductStyle.Healthy,
    issue: CharityIssue.ShelteredWorkshop,
    dateAdded: '2025-09-20',
    sales: 98,
  },
  {
    id: 'prod4',
    name: '馨希望手工餅乾',
    organization: '勵馨基金會',
    price: 300,
    image: 'https://images.pexels.com/photos/4110538/pexels-photo-4110538.jpeg',
    type: ProductType.Cookie,
    style: ProductStyle.Creative,
    issue: CharityIssue.WomenEmployment,
    dateAdded: '2025-08-30',
    sales: 420,
  },
  {
    id: 'prod5',
    name: '大地果乾磅蛋糕',
    organization: 'TFT 偏鄉共好廚房',
    price: 450,
    image: 'https://images.pexels.com/photos/1938268/pexels-photo-1938268.jpeg',
    type: ProductType.Cake,
    style: ProductStyle.Healthy,
    issue: CharityIssue.RuralEducation,
    dateAdded: '2025-10-01',
    sales: 55,
  },
  {
    id: 'prod6',
    name: '聖誕薑餅人組合',
    organization: '喜憨兒基金會',
    price: 380,
    image: 'https://images.pexels.com/photos/3309805/pexels-photo-3309805.jpeg',
    type: ProductType.Cookie,
    style: ProductStyle.Festive,
    issue: CharityIssue.ShelteredWorkshop,
    dateAdded: '2025-09-25',
    sales: 210,
  },
  {
    id: 'prod7',
    name: '婦女手作巧克力塔',
    organization: '勵馨基金會',
    price: 550,
    image: 'https://images.pexels.com/photos/29642313/pexels-photo-29642313.jpeg',
    type: ProductType.Cake,
    style: ProductStyle.Creative,
    issue: CharityIssue.WomenEmployment,
    dateAdded: '2025-09-18',
    sales: 180,
  },
  {
    id: 'prod8',
    name: '感恩節南瓜派點心盒',
    organization: '伊甸基金會',
    price: 480,
    image: 'https://images.pexels.com/photos/2035738/pexels-photo-2035738.jpeg',
    type: ProductType.GiftBox,
    style: ProductStyle.Festive,
    issue: CharityIssue.ShelteredWorkshop,
    dateAdded: '2025-09-10',
    sales: 120,
  },
];